# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e4302bb81a6f24d88d3c23052d556af7322fda19a18c199a59e23b3557799131b3ffd28dc0487c19e721bf13d12811b8cd3c8b23f701d9fca5b4f7f502d7bc5

test:
  secret_key_base: 01b3c1d294b40dc71c1df0cb3c6c62619645a031fbe1bbd687402ea0d6216eeaf04ce3e7cdda22d49c993b53cd002e879a97d57bca8d4adf1032bc65e503c8b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
